# Change baseurl before deploy
baseurl = "https://blog.sunmkt.uk"
languageCode = "zh-cn" # Workaround for upstream, copy i18n/zh.toml to i18n/zh-cn.toml
title = "Sunset 的重构博客"
disablePathToLower = true

# Build timeout
timeout = "600s"

# GitInfo
# https://gohugo.io/methods/page/gitinfo/
# https://gohugo.io/configuration/front-matter/#dates
# lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
enableGitInfo = true

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "sunset-blog-hugo"

[pagination]
pagerSize = 10

[outputFormats.RSS]
# mediatype = "application/rss"
baseName = "feed"

[services.rss]
limit = 30 # RSS 包含最近的 30 篇

# Copy source code to output
# Also see layouts\_default\single.source_hugo_generated.txt
[outputs]
page = ["HTML", "Source"]

[outputFormats.Source]
mediaType = "text/plain"
baseName = "source_hugo_generated"
isPlainText = true
path = ""
