# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = false
favicon = "/favicon.ico"

[footer]
since = 2024
customText = "ä½œè€…å¯¹äºå› ä½¿ç”¨æˆ–è§£è¯»æ‰€æä¾›å†…å®¹è€Œå¯¼è‡´çš„ä»»ä½•ç›´æ¥æˆ–é—´æ¥åæœä¸æ‰¿æ‹…ä»»ä½•è´£ä»»ã€‚"

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04:05"

[sidebar]
emoji = "ğŸ‡ºğŸ‡¦"
subtitle = "Sunset Edu. & Tech. Group çš„é¦–å¸­ç¨‹åºå‘˜"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "é™¤éå¦æœ‰è¯´æ˜ï¼Œæ­¤å†…å®¹ä½¿ç”¨ CC BY-SA 4.0 è®¸å¯ã€‚"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "img/cover_template_1.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = "https://waline.sunmkt.uk"
# lang = "zh-CN"
# avatar = ""
emoji = ["https://unpkg.com/@waline/emojis@1.2.0/tw-emoji"]
reaction = [
    "https://unpkg.com/@waline/emojis@1.2.0/tw-emoji/1f60d.png",
    "https://unpkg.com/@waline/emojis@1.2.0/tw-emoji/1f642.png",
    "https://unpkg.com/@waline/emojis@1.2.0/tw-emoji/1f641.png",
    "https://unpkg.com/@waline/emojis@1.2.0/tw-emoji/1f62d.png",
]
requiredMeta = ["name"]
search = false
turnstileKey = "0x4AAAAAAAZ0ouYIQ46lj2Up"

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "SunsetMkt/Blog-hugo"
repoID = "R_kgDONNixWA"
category = "Announcements"
categoryID = "DIC_kwDONNixWM4CkLtz"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 1

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
