name = "sunset-blog-hugo"
compatibility_date = "2025-11-01"
main = "./worker/index.js"
workers_dev = true
keep_vars = true
send_metrics = false
minify = true

[build]
command = "chmod a+x workers_build.sh && ./workers_build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
binding = "ASSETS"
run_worker_first = ["/api/*"]
